spring.application.name=quizApp
spring.datasource.url=jdbc:postgresql://localhost:5433/quiz
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/liquibase-changelog.xml
jwt.token= 416536cde3151b049ff90debb5aa11e5d7c73b5d